version: '3.9'

services:
  backend:
    build: .
    ports:
      - "${LOCAL_PORT}:${LOCAL_PORT}"
    environment:
      LOCAL_PORT: ${LOCAL_PORT} 
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
    depends_on:
      - db
    restart: on-failure  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
